// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4A-FiPcGSbkPVdL0QnVLqdL9cE29Op38',
    appId: '1:802555320010:web:62b745004067cb0f844633',
    messagingSenderId: '802555320010',
    projectId: 'shoesly-12b06',
    authDomain: 'shoesly-12b06.firebaseapp.com',
    storageBucket: 'shoesly-12b06.appspot.com',
    measurementId: 'G-9RWYSXHDBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBurFB1u5-osUGPSguMjI7zpSMuKC8C31M',
    appId: '1:802555320010:android:a78763d5bd65abc0844633',
    messagingSenderId: '802555320010',
    projectId: 'shoesly-12b06',
    storageBucket: 'shoesly-12b06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Uh00LLvBCnJV0CE_fxyB_SBrrlreis0',
    appId: '1:802555320010:ios:4a1bad7beb979fcf844633',
    messagingSenderId: '802555320010',
    projectId: 'shoesly-12b06',
    storageBucket: 'shoesly-12b06.appspot.com',
    iosBundleId: 'com.example.shoesly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Uh00LLvBCnJV0CE_fxyB_SBrrlreis0',
    appId: '1:802555320010:ios:4a1bad7beb979fcf844633',
    messagingSenderId: '802555320010',
    projectId: 'shoesly-12b06',
    storageBucket: 'shoesly-12b06.appspot.com',
    iosBundleId: 'com.example.shoesly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4A-FiPcGSbkPVdL0QnVLqdL9cE29Op38',
    appId: '1:802555320010:web:34d1d445d0ac0b76844633',
    messagingSenderId: '802555320010',
    projectId: 'shoesly-12b06',
    authDomain: 'shoesly-12b06.firebaseapp.com',
    storageBucket: 'shoesly-12b06.appspot.com',
    measurementId: 'G-V8BEE9J2JP',
  );
}
